name: Publish Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      - name: Gen release file
        run: |
          npx less-write-changelog

      - name: Commit and push changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "docs(CHANGELOG): update changelog [skip ci]"
          git push origin HEAD:main

      - name: Release to Github
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          body_path: RELEASE.md
          files: |
            less-write-http-server-linux
            less-write-http-server-win.exe
